name: flutter_iptv_web_server
description: Web backend server for Flutter IPTV
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  http: ^1.1.2
  sqlite3: ^2.4.0
  path: ^1.8.3
  args: ^2.4.2

dev_dependencies:
  lints: ^3.0.0